# Generated by Django 2.2 on 2021-10-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='answertext',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='answertext',
            old_name='UserAnswer',
            new_name='user_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Survey',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='DateCreate',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='DateEnd',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='DateStart',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='User',
            new_name='user',
        ),
    ]
